# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
repos:
# autopepe sucks until they fix the "colon slice issue"
# -   repo: https://github.com/pre-commit/mirrors-autopep8
#     rev: v1.4.4
#     hooks:
#     -   id: autopep8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.0.1
    hooks:
    - id: check-ast
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: check-json
    - id: check-symlinks
    - id: check-yaml
    - id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black
# -   repo: https://github.com/timothycrosley/isort
#     rev: 4.3.21
#     hooks:
#     - id: isort
# -   repo: https://github.com/pre-commit/mirrors-pylint
#     rev: v2.4.4
#     hooks:
#     -   id: pylint
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.740
#     hooks:
#     -   id: mypy
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.4.3
    hooks:
    -   id: pyupgrade
# -   repo: https://github.com/asottile/dead
#     rev: v0.0.8-1
#     hooks:
#     -   id: dead
# -   repo: git://github.com/detailyang/pre-commit-shell
#     rev: 1.0.5
#     hooks:
#     - id: shell-lint
#       args: [--format=json]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1  # Use the ref you want to point at
    hooks:
    -   id: python-use-type-annotations
-   repo: https://github.com/asottile/yesqa
    rev: v1.1.0
    hooks:
    -   id: yesqa
-   repo: https://github.com/ahonnecke/blacklist
    rev: v0.0.3
    hooks:
    -   id: blacklist
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
    -   id: flake8
